// Embeds the vite-built single-file UI (ui/dist/index.html) as a TypeScript
// module so every runtime — stdio, Node HTTP, and Cloudflare Workers (no
// filesystem) — can serve it from the compiled bundle.
//
// Run via: npm run build:ui   (vite build && node scripts/embed-ui.mjs)
// The generated module is committed so plain `npm run build` (tsc) and CI
// don't need vite unless ui/ changes.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(path.join(root, "ui/dist/index.html"), "utf-8");
const outDir = path.join(root, "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "invoice-card-html.ts"),
  `// GENERATED by scripts/embed-ui.mjs from ui/dist/index.html — do not edit.\n` +
    `// Rebuild with: npm run build:ui\n` +
    `export const INVOICE_CARD_HTML = ${JSON.stringify(html)};\n`,
);
console.log("Embedded ui/dist/index.html -> src/generated/invoice-card-html.ts");
